### ISSUE TITLE
updating wiped my custom settings

### ISSUE THREAD

**Issue by DrMacabre** [Zyin055/Config-Presets-Script-OLD-#3]
hi,

I updated the extension today to find out it wiped all the settings i had carefully customized for my needs. That's less than convenient.

May be not updating the config.json when updating the script would be a good idea.

**Comment by DrMacabre** [comment]
It would be a great addition to the script to simply be able to save current settings to the config.json instead of editing it by hand.

**Comment by Zyin055** [comment]
This repo the old version of this script and is legacy. It's been updated to an extension which won't wipe your config.json: https://github.com/Zyin055/Config-Presets

**Comment by DrMacabre** [comment]
ok thank you
So i submitted in the wrong repo because im using the extension from automatic 1111 and it still wiped my config.
